os: Visual Studio 2017
environment:
    matrix:
      - channel: nightly
        target: i686-pc-windows-msvc
      - channel: nightly
        target: x86_64-pc-windows-msvc
install:
  - appveyor DownloadFile https://win.rustup.rs -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup component add clippy-preview
build: false
test_script:
  - cargo clippy
  - cargo test
