language: rust
rust:
  - nightly
os:
  - linux
  - osx
  - windows
before_install:
  - rustup component add clippy
script:
  - cargo clippy --verbose -- -D warnings
  - cargo test
notifications:
    email: false
