jobs:
  - job: Rustfmt
    strategy:
        matrix:
            Linux:
                imageName: ubuntu-latest
            macOS:
                imageName: macOS-latest
            Windows:
                imageName: windows-latest
    pool:
        vmImage: $(imageName)
    steps:
      - template: .azure-pipelines/install-rust.yml
      - script: rustup component add rustfmt
        displayName: Install Rustfmt
      - script: cargo fmt -- --check
        displayName: Run Rustfmt checks
  - job: Clippy
    strategy:
        matrix:
            Linux:
                imageName: ubuntu-latest
            macOS:
                imageName: macOS-latest
            Windows:
                imageName: windows-latest
    pool:
        vmImage: $(imageName)
    steps:
      - template: .azure-pipelines/install-rust.yml
      - script: rustup component add clippy
        displayName: Install Clippy
      - script: cargo clippy --all-targets --all-features -- -D warnings
        displayName: Run Clippy checks
  - job: Tests
    strategy:
        matrix:
            Linux:
                imageName: ubuntu-latest
            macOS:
                imageName: macOS-latest
            Windows:
                imageName: windows-latest
    pool:
        vmImage: $(imageName)
    steps:
      - template: .azure-pipelines/install-rust.yml
      - script: cargo test
        displayName: Run tests
  - job: Coverage
    pool:
        vmImage: ubuntu-latest
    steps:
      - template: .azure-pipelines/install-rust.yml
      - script: cargo install cargo-tarpaulin
        displayName: Install Tarpaulin
      - script: cargo tarpaulin --out Xml
        displayName: Run coverage tests
      - task: PublishCodeCoverageResults@1
        displayName: Publish coverage result
        inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: cobertura.xml
