strategy:
    matrix:
        linux:
            imageName: ubuntu-latest
        mac:
            imageName: macOS-latest
        windows:
            imageName: windows-latest
    maxParallel: 3
pool:
    vmImage: $(imageName)
steps:
  - script: |
        curl -f https://sh.rustup.rs | bash -s -- -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install Rust (*nix)
    condition: ne(variables['Agent.OS'], 'Windows_NT')
  - script: |
        curl -fo rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y
        echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Install Rust (Windows)
    condition: eq(variables['Agent.OS'], 'Windows_NT')
  - script: rustup component add clippy
    displayName: Install Clippy
  - script: cargo clippy --all-targets --all-features --verbose -- -D warnings
    displayName: Run Clippy checks
  - script: cargo test --verbose
    displayName: Run tests
