jobs:
  - job: Rustfmt
    strategy:
        matrix:
            Linux:
                imageName: ubuntu-latest
            macOS:
                imageName: macOS-latest
            Windows:
                imageName: windows-latest
    pool:
        vmImage: $(imageName)
    steps:
      - template: .azure-pipelines/install-rust.yml
      - script: rustup component add rustfmt
        displayName: Install Rustfmt
      - script: cargo fmt -- --check
        displayName: Run Rustfmt checks
  - job: Clippy
    strategy:
        matrix:
            Linux:
                imageName: ubuntu-latest
            macOS:
                imageName: macOS-latest
            Windows:
                imageName: windows-latest
    pool:
        vmImage: $(imageName)
    steps:
      - template: .azure-pipelines/install-rust.yml
      - script: rustup component add clippy
        displayName: Install Clippy
      - script: cargo clippy --all-targets --all-features -- -D warnings
        displayName: Run Clippy checks
  - job: Tests
    strategy:
        matrix:
            Linux:
                imageName: ubuntu-latest
            macOS:
                imageName: macOS-latest
            Windows:
                imageName: windows-latest
    pool:
        vmImage: $(imageName)
    steps:
      - template: .azure-pipelines/install-rust.yml
      - script: cargo install cargo2junit
        displayName: Install cargo2junit
        condition: eq(variables['Agent.OS'], 'Linux')
      - script: cargo test -- -Z unstable-options --format json | tee >(cargo2junit > test-results.xml)
        displayName: Run tests (Linux)
        condition: eq(variables['Agent.OS'], 'Linux')
        continueOnError: true
      - script: cargo test
        displayName: Run tests (macOS, Windows)
        condition: ne(variables['Agent.OS'], 'Linux')
      - task: PublishTestResults@2
        displayName: Publish test results
        condition: eq(variables['Agent.OS'], 'Linux')
        inputs:
            testResultsFiles: test-results.xml
  - job: Coverage
    container:
        image: xd009642/tarpaulin
        options: --security-opt seccomp=unconfined
    steps:
      - template: .azure-pipelines/install-rust.yml
      - script: cargo tarpaulin --out Xml
        displayName: Run coverage tests
      - task: PublishCodeCoverageResults@1
        displayName: Publish coverage result
        inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: cobertura.xml
