strategy:
    matrix:
        linux:
            imageName: ubuntu-latest
        mac:
            imageName: macOS-latest
        windows:
            imageName: windows-latest
pool:
    vmImage: $(imageName)
steps:
  - script: |
        curl -f https://sh.rustup.rs | bash -s -- -y
        echo "##vso[task.prependpath]$HOME/.cargo/bin"
    displayName: Install Rust
    condition: eq(variables['Agent.OS'], 'Darwin')
  - script: rustup component add clippy
    displayName: Install Clippy
    condition: eq(variables['Agent.OS'], 'Darwin')
  - script: rustup component add rustfmt
    displayName: Install Rustfmt
    condition: eq(variables['Agent.OS'], 'Darwin')
  - script: cargo fmt -- --check
    displayName: Run Rustfmt checks
  - script: cargo clippy --all-targets --all-features -- -D warnings
    displayName: Run Clippy checks
  - script: cargo test
    displayName: Run tests
