strategy:
    matrix:
        linux:
            imageName: ubuntu-latest
        mac:
            imageName: macOS-latest
        windows:
            imageName: windows-latest
pool:
    vmImage: $(imageName)
steps:
  - script: cargo clippy --all-targets --all-features --verbose -- -D warnings
    displayName: Run Clippy checks
  - script: cargo test --verbose
    displayName: Run tests
