name: CI
on: push
jobs:
    rustfmt:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: hecrj/setup-rust-action@v1.1.0
            with:
              - components: rustfmt
          - uses: actions/checkout@v1
          - name: Run Rustfmt checks
            run: cargo fmt -- --check
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
            fail-fast: false
    clippy:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: hecrj/setup-rust-action@v1.1.0
            with:
              - components: clippy
          - uses: actions/checkout@v1
          - name: Run Clippy checks
            run: cargo clippy --all-targets --all-features -- -D warnings
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
            fail-fast: false
    test:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: hecrj/setup-rust-action@v1.1.0
          - uses: actions/checkout@v1
          - name: Run tests
            run: cargo test
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
            fail-fast: false
