name: CI
on: push
jobs:
    rustfmt:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/toolchain@v1
            with:
                components: rustfmt
          - run: cargo fmt -- --check
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    clippy:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/toolchain@v1
            with:
                components: clippy
          - run: cargo clippy --all-targets --all-features -- -W clippy::pedantic -A clippy::cast-possible-truncation -A clippy::cast-possible-wrap -A clippy::cast-precision-loss -A clippy::cast-sign-loss -A clippy::must-use-candidate -A clippy::non-ascii-literal -D warnings
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    tests:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/toolchain@v1
          - run: cargo test
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
