name: CI
on: push
jobs:
    rustfmt:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v3
          - run: cargo fmt --all -- --check
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    clippy:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v3
          - run: cargo clippy --workspace --all-targets --all-features -- -D warnings
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    tests:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v3
          - run: cargo test --workspace
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: rustup component add llvm-tools
          - run: cargo install cargo-llvm-cov
          - run: cargo llvm-cov --lcov --workspace --output-path coverage/lcov.info
          - uses: codecov/codecov-action@v3
            with:
                files: coverage/lcov.info
          - uses: coverallsapp/github-action@master
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

